require:
  - rubocop-rails
  - rubocop-rspec

inherit_from: ./lib/rubocop/blacklist.yml

AllCops:
  TargetRubyVersion: 3.0.0
  NewCops: enable

Layout/LineLength:
  Max: 110
  IgnoredPatterns: ['(\A|\s)#']

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']
  Exclude:
    - 'config/routes.rb'
    - 'config/environments/*.rb'

Style/MixinUsage:
  Exclude:
    - 'features/step_definitions/*.rb'

Lint/MissingSuper:
  Enabled: false

# rubocop-rspec gem excludes
RSpec/NamedSubject:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/NestedGroups:
  Max: 6

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/api_wrappers/compliance_checker_api/*.rb'
    - 'spec/api_wrappers/payments_api/*.rb'
    - 'spec/api_wrappers/vehicles_checker_api/*.rb'
    - 'spec/requests/application_controller/*.rb'

RSpec/ExampleLength:
  Enabled: false
